tasks:
  - name: Install Backend and Start FastApi
    init: cd backend && pip install -r requirements_dev.txt
    command: uvicorn handler:app --reload
  - name: Install Frontend and Start NextJs
    init: cd frontend && npm install
    command: npm run dev

ports:
  - port: 8000
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - dbaeumer.vscode-eslint
