tasks:
  - name: Install PNPM
    init: |
      npm install -g pnpm
      gp sync-done pnpm # wait following to install pnpm
  - name: Init Monorepo
    init: gp sync-await pnpm
    command: pnpm install
  - name: Install Frontend and Start NextJs
    init: |
      gp sync-await pnpm
      cd frontend
      pnpm install
      cd ..
    command: |
      cd frontend
      pnpm run dev
  - name: Install Backend and Start FastApi
    init: |
      cd backend
      pip install -r requirements_dev.txt
      cd ..
    command: |
      cd backend
      uvicorn handler:app --reload

ports:
  - port: 8000
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - ms-python.python
    - dbaeumer.vscode-eslint
